import 'dart:convert';
import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:zeroxkey_crypto/src/crypto.dart';
import 'package:zeroxkey_crypto/src/hpke.dart';
import 'package:zeroxkey_encoding/zeroxkey_encoding.dart';

void main() {
  group('HPKE info isolation', () {
    const plainText = '0xkey-hpke-info-isolation-roundtrip-fixture';
    late Uint8List plainTextBuf;
    late Uint8List targetKeyBuf;
    late String receiverPriv;

    setUp(() {
      final receiver = generateP256KeyPair();
      receiverPriv = receiver.privateKey;
      targetKeyBuf = uncompressRawPublicKey(
        uint8ArrayFromHexString(receiver.publicKey),
      );
      plainTextBuf = Uint8List.fromList(utf8.encode(plainText));
    });

    test('0xkey_hpke roundtrip succeeds', () {
      final encrypted = hpkeEncrypt(
        plainTextBuf: plainTextBuf,
        targetKeyBuf: targetKeyBuf,
        hpkeInfo: zeroxkeyHpkeInfo,
      );
      final formatted =
          jsonDecode(formatHpkeBuf(encrypted)) as Map<String, dynamic>;

      final decrypted = hpkeDecrypt(
        ciphertextBuf:
            uint8ArrayFromHexString(formatted['ciphertext'] as String),
        encappedKeyBuf:
            uint8ArrayFromHexString(formatted['encappedPublic'] as String),
        receiverPriv: receiverPriv,
        hpkeInfo: zeroxkeyHpkeInfo,
      );

      expect(utf8.decode(decrypted), plainText);
    });

    test('0xkey_hpke ciphertext cannot be decrypted via legacy schedule', () {
      final encrypted = hpkeEncrypt(
        plainTextBuf: plainTextBuf,
        targetKeyBuf: targetKeyBuf,
        hpkeInfo: zeroxkeyHpkeInfo,
      );
      final formatted =
          jsonDecode(formatHpkeBuf(encrypted)) as Map<String, dynamic>;

      expect(
        () => hpkeDecrypt(
          ciphertextBuf:
              uint8ArrayFromHexString(formatted['ciphertext'] as String),
          encappedKeyBuf:
              uint8ArrayFromHexString(formatted['encappedPublic'] as String),
          receiverPriv: receiverPriv,
        ),
        throwsA(isA<Exception>()),
      );
    });

    test('cross-language golden vector decrypts in Dart', () {
      // Golden vector generated by the reference crypto implementation with
      // hpkeInfo = 0xkey_hpke.
      const receiverPriv =
          '01d95d256f744b2a855fe2036ec1074c726445f1382f53580a17ce3296cc2dec';
      const plainText = 'cross-lang-hpke-golden-vector-v1';
      const ciphertext =
          'a146d9d310373378d4c9209f145e2d9a76ef914056e7e89cf1dd9dbf358f203d68f28fbebdea6c46798d3ff930956857';
      const encappedPublic =
          '04a6b27faead5e7e2fb18ed155a54115d718235cd72ed13e1ae2c7ece7f4c5b5d36d0a1ebf5d50da661d8a71e2d6bb7407376f4eacc8365b82b795a660291abf07';

      final decrypted = hpkeDecrypt(
        ciphertextBuf: uint8ArrayFromHexString(ciphertext),
        encappedKeyBuf: uint8ArrayFromHexString(encappedPublic),
        receiverPriv: receiverPriv,
        hpkeInfo: zeroxkeyHpkeInfo,
      );

      expect(utf8.decode(decrypted), plainText);
    });

    test('legacy ciphertext cannot be decrypted via 0xkey_hpke', () {
      final encrypted = hpkeEncrypt(
        plainTextBuf: plainTextBuf,
        targetKeyBuf: targetKeyBuf,
      );
      final formatted =
          jsonDecode(formatHpkeBuf(encrypted)) as Map<String, dynamic>;

      expect(
        () => hpkeDecrypt(
          ciphertextBuf:
              uint8ArrayFromHexString(formatted['ciphertext'] as String),
          encappedKeyBuf:
              uint8ArrayFromHexString(formatted['encappedPublic'] as String),
          receiverPriv: receiverPriv,
          hpkeInfo: zeroxkeyHpkeInfo,
        ),
        throwsA(isA<Exception>()),
      );
    });
  });
}
