// tool/gen_git_overrides.dart
//
// Generates a ready-to-paste pubspec snippet for consuming this SDK as a Git
// dependency (integration "方案 1"). Because this is a pub workspace whose
// packages depend on each other by version (`^x`), a consumer that only Git-
// references `zeroxkey_sdk_flutter` cannot resolve the sibling packages from
// pub.dev. This tool emits the `dependencies:` entry plus the matching
// `dependency_overrides:` for every sibling so resolution succeeds.
//
// Usage:
//   dart run tool/gen_git_overrides.dart [--ref <git-ref>] [--url <repo-url>]
//                                        [--main <package-name>] [--write <file>]
//
// Examples:
//   dart run tool/gen_git_overrides.dart --ref prod-20260624
//   make git-overrides REF=prod-20260624

import 'dart:io';

import 'changeset_lib.dart';

const _defaultUrl = 'https://github.com/0xkey-io/sdk-dart.git';
const _defaultMain = 'zeroxkey_sdk_flutter';

String? _argValue(List<String> args, String name) {
  final flag = '--$name';
  final idx = args.indexOf(flag);
  if (idx >= 0 && idx + 1 < args.length) return args[idx + 1];
  for (final a in args) {
    if (a.startsWith('$flag=')) return a.substring(flag.length + 1);
  }
  return null;
}

void main(List<String> args) {
  final ref = _argValue(args, 'ref') ?? 'main';
  final url = _argValue(args, 'url') ?? _defaultUrl;
  final mainPkg = _argValue(args, 'main') ?? _defaultMain;
  final writePath = _argValue(args, 'write');

  final packages = discoverPackages();
  if (packages.isEmpty) {
    stderr.writeln('No packages found under "$packagesRootDirName/".');
    exitCode = 1;
    return;
  }

  final mainInfo = packages.where((p) => p.name == mainPkg).toList();
  if (mainInfo.isEmpty) {
    stderr.writeln('Main package "$mainPkg" not found. Available: '
        '${packages.map((p) => p.name).join(', ')}');
    exitCode = 1;
    return;
  }

  final buffer = StringBuffer()
    ..writeln('# Generated by tool/gen_git_overrides.dart')
    ..writeln('# ref: $ref  url: $url')
    ..writeln('dependencies:')
    ..writeln('  $mainPkg:')
    ..writeln('    git:')
    ..writeln('      url: $url')
    ..writeln('      path: ${mainInfo.single.path}')
    ..writeln('      ref: $ref')
    ..writeln()
    ..writeln('dependency_overrides:');

  for (final pkg in packages) {
    if (pkg.name == mainPkg) continue;
    buffer
      ..writeln('  ${pkg.name}:')
      ..writeln('    git:')
      ..writeln('      url: $url')
      ..writeln('      path: ${pkg.path}')
      ..writeln('      ref: $ref');
  }

  final output = buffer.toString();

  if (writePath != null) {
    File(writePath).writeAsStringSync(output);
    stdout.writeln('Wrote $writePath');
  } else {
    stdout.write(output);
  }
}
